version: "3.8"

services:
  app:
    container_name: wordle-node
    image: app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 80:3000
    environment:
      - DEBUG=1
      - REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY=
