# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://cookie.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2de0e5fe1f1543c28eaf7ffea7447ea7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_efa7559edde243f38c989528e8de4248 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cookie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2de0e5fe1f1543c28eaf7ffea7447ea7 }}/wordle-node:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a8576ccd044c40babbf755fc57c76c3f }}
        images: 'cookie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2de0e5fe1f1543c28eaf7ffea7447ea7 }}/wordle-node:${{ github.sha }}'